package com.truszczynski.swingfreecourse;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author szymon
 */
public class Ypanel_lesson extends javax.swing.JPanel {

    private JButton yBtn;
    private JLabel textLabel, imgLabel;

    private JTextField tf;
    private JTextArea ta;
    private JScrollPane sp;

    private JComboBox petListCb, sexCb;
    private JList jList;

    private JSeparator separator;

    private JCheckBox insuranceCheckBox, shnitzelCheckBox;

    private List<JRadioButton> radioButtonList;
    private ButtonGroup buttonGroup;

    /**
     * Creates new form ypanel_lesson
     */
    public Ypanel_lesson() {
        setSize(500, 500);
        setBackground(Color.DARK_GRAY);
        //initComponents();
        addBtnAndLabel();
        addTextFieldAndTextArea();
        addComboboxAndJlist();
        addJSeparator();
        addCheckbox();
        addRadioButton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void addBtnAndLabel() {
        yBtn = new JButton("my btn");
        add(yBtn);

        textLabel = new JLabel("text label and img label->");
        imgLabel = new JLabel();
        addImgToLabel("label.png", imgLabel);
        add(textLabel);
        add(imgLabel);

    }

    private void addImgToLabel(String iconName, JLabel jLabel) {
        jLabel.setIcon(new ImageIcon("src/main/resources/" + iconName));
        repaint();
        revalidate();
    }

    private void addTextFieldAndTextArea() {
        tf = new JTextField("enter text here", 16);
        add(tf);

        ta = new JTextArea(11, 20);
        sp = new JScrollPane(ta);
        add(sp);
    }

    private void addComboboxAndJlist() {
        String[] petStrings = {"Bird", "Cat", "Dog", "Rabbit", "Pig"};

        petListCb = new JComboBox(petStrings);
        add(petListCb);

        String[] sexStrings = {"Male", "Female"};
        sexCb = new JComboBox(sexStrings);
        add(sexCb);

        String[] itemStrings = {"Item 1", "Item 2", "Item 3"};
        jList = new JList(itemStrings);
        jList.setPreferredSize(new Dimension(150, 80));
        add(jList);
    }

    private void addJSeparator() {
        separator = new JSeparator(JSeparator.VERTICAL);
        separator.setPreferredSize(new Dimension(1, 750));
        add(separator);
    }

    private void addCheckbox() {
        insuranceCheckBox = new JCheckBox("Do You have insurance?");
        shnitzelCheckBox = new JCheckBox("Do You like shnitzel?");
        shnitzelCheckBox.setSelected(true);
        add(insuranceCheckBox);
        add(shnitzelCheckBox);

    }

    private void addRadioButton() {
        List<String> radioButtonStringsList = new ArrayList<>(Arrays.asList("radio 1", "some option", "bla bla", "lorem ipsum"));
        createOneSetOfJRadioButtons(radioButtonStringsList, new ButtonGroup());
        List<String> radioButtonStringsList2 = new ArrayList<>(Arrays.asList("Alojzy", "Mroczny rycerz"));
        createOneSetOfJRadioButtons(radioButtonStringsList2, new ButtonGroup());
    }

    private void createOneSetOfJRadioButtons(List<String> stringList, ButtonGroup buttonGroup) {
        stringList.forEach(string -> {
            JRadioButton jRadioButton = new JRadioButton(string);
            buttonGroup.add(jRadioButton);
            add(jRadioButton);
        });
    }
}
